#!/usr/bin/env python3
"""Generates MessageFieldMap.swift: for every message in the vendored proto
set, the message-typed fields (field number → fully-qualified type name).

This powers generic wire-format walking in Swift (e.g. finding and rewriting
every TSP.Reference in a payload) without needing protobuf descriptors at
runtime. `extend` blocks are merged into the extended message's table.

The table is emitted as a compact string parsed at runtime — large Swift
dictionary literals are slow to type-check.
"""
import re
import sys
from pathlib import Path

version = sys.argv[1] if len(sys.argv) > 1 else "14.4"
repo_root = Path(__file__).resolve().parent.parent
proto_dir = repo_root / "proto" / version
out_path = repo_root / "Sources" / "KeynoteSchemas" / "MessageFieldMap.swift"

FIELD_RE = re.compile(
    r"^\s*(optional|required|repeated)\s+(\.[\w.]+)\s+\w+\s*=\s*(\d+)"
)
MESSAGE_RE = re.compile(r"^\s*message\s+(\w+)\s*\{")
EXTEND_RE = re.compile(r"^\s*extend\s+(\.[\w.]+)\s*\{")
ENUM_RE = re.compile(r"^\s*enum\s+(\w+)\s*\{")
PACKAGE_RE = re.compile(r"^package\s+([\w.]+);")

# message full name -> {field number: field type full name}
tables: dict[str, dict[int, str]] = {}

for proto in sorted(proto_dir.glob("*.proto")):
    package = ""
    # stack of (kind, full_name) where kind is 'message'|'extend'|'enum'|'block'
    stack: list[tuple[str, str]] = []
    for line in proto.read_text().splitlines():
        stripped = line.split("//")[0]
        if m := PACKAGE_RE.match(stripped):
            package = m.group(1)
            continue
        if m := MESSAGE_RE.match(stripped):
            parent = next(
                (name for kind, name in reversed(stack) if kind == "message"), None
            )
            full = f"{parent}.{m.group(1)}" if parent else f"{package}.{m.group(1)}"
            stack.append(("message", full))
            tables.setdefault(full, {})
            continue
        if m := EXTEND_RE.match(stripped):
            stack.append(("extend", m.group(1).lstrip(".")))
            continue
        if ENUM_RE.match(stripped):
            stack.append(("enum", ""))
            continue
        if m := FIELD_RE.match(stripped):
            target = next(
                (
                    name
                    for kind, name in reversed(stack)
                    if kind in ("message", "extend")
                ),
                None,
            )
            if target is not None:
                tables.setdefault(target, {})[int(m.group(3))] = m.group(2).lstrip(".")
        if "{" in stripped and not (
            MESSAGE_RE.match(stripped) or EXTEND_RE.match(stripped) or ENUM_RE.match(stripped)
        ):
            # oneof or other unnamed block — track for brace balance
            if stripped.count("{") > stripped.count("}"):
                stack.append(("block", ""))
            continue
        if "}" in stripped and stripped.count("}") > stripped.count("{"):
            if stack:
                stack.pop()

non_empty = {name: fields for name, fields in tables.items() if fields}
lines_out = []
for name in sorted(non_empty):
    fields = ",".join(
        f"{num}:{type_name}" for num, type_name in sorted(non_empty[name].items())
    )
    lines_out.append(f"{name}|{fields}")

table_string = "\\n".join(lines_out)

swift = f'''// Generated by scripts/gen-fieldmap.py from proto/{version}/ — do not edit.
// For every message: its message/enum-typed fields (field number → type name).
// Backing store is a compact string, parsed once — large dictionary literals
// are slow to compile.

public enum MessageFieldMap {{
    /// message full name → (field number → field type full name)
    public static let messageFields: [String: [Int: String]] = {{
        var result: [String: [Int: String]] = [:]
        result.reserveCapacity({len(non_empty)})
        for line in rawTable.split(separator: "\\n") {{
            let parts = line.split(separator: "|", maxSplits: 1)
            var fields: [Int: String] = [:]
            for entry in parts[1].split(separator: ",") {{
                let kv = entry.split(separator: ":", maxSplits: 1)
                fields[Int(kv[0])!] = String(kv[1])
            }}
            result[String(parts[0])] = fields
        }}
        return result
    }}()

    private static let rawTable = "{table_string}"
}}
'''
out_path.write_text(swift)
total_fields = sum(len(f) for f in non_empty.values())
print(f"Wrote {out_path}: {len(non_empty)} messages, {total_fields} typed fields")
