#!/usr/bin/env python3
"""Generates TSPRegistry.swift from keynote-parser's mapping.py.

The mapping file (vendored at proto/<version>/mapping.py) contains
TSPRegistryMapping: a dict of Keynote's numeric message type IDs to
"Package.MessageName" strings. Swift-protobuf names the generated types
Package_MessageName, so the conversion is mechanical.
"""
import re
import sys
from pathlib import Path

version = sys.argv[1] if len(sys.argv) > 1 else "14.4"
repo_root = Path(__file__).resolve().parent.parent
mapping_path = repo_root / "proto" / version / "mapping.py"
out_path = repo_root / "Sources" / "KeynoteSchemas" / "TSPRegistry.swift"

text = mapping_path.read_text()
block = re.search(r"TSPRegistryMapping = \{(.*?)\n\}", text, re.DOTALL).group(1)
entries = re.findall(r"(\d+):\s*\"([\w.]+)\"", block)

# Swift-protobuf flattens the proto *package* into the type name with
# underscores (TSCH.PreUFF → TSCH_PreUFF_...), while *nested messages* stay
# nested via dots (TST.GroupByArchive.GroupNodeArchive →
# TST_GroupByArchive.GroupNodeArchive). Read the actual package names so the
# two cases can be told apart.
packages = set()
for proto in (repo_root / "proto" / version).glob("*.proto"):
    m = re.search(r"^package ([\w.]+);", proto.read_text(), re.MULTILINE)
    if m:
        packages.add(m.group(1))


def swift_type_name(qualified: str) -> str:
    package = max(
        (p for p in packages if qualified.startswith(p + ".")),
        key=len,
        default=None,
    )
    if package is None:
        return qualified.replace(".", "_")
    prefix = package.replace(".", "_")
    remainder = qualified[len(package) + 1:]
    # First component after the package joins with '_'; deeper nesting uses '.'
    parts = remainder.split(".")
    return prefix + "_" + parts[0] + ("." + ".".join(parts[1:]) if len(parts) > 1 else "")

lines = [
    "// Generated by scripts/gen-registry.py from proto/%s/mapping.py — do not edit." % version,
    "// Maps Keynote's numeric message type IDs (MessageInfo.type) to schema types.",
    "",
    "import SwiftProtobuf",
    "",
    "public enum TSPRegistry {",
    "    public static let schemaVersion = \"%s\"" % version,
    "",
    "    public static let messageTypes: [UInt32: SwiftProtobuf.Message.Type] = [",
]
for type_id, name in entries:
    lines.append("        %s: %s.self," % (type_id, swift_type_name(name)))
lines += [
    "    ]",
    "",
    "    public static func messageType(for typeID: UInt32) -> SwiftProtobuf.Message.Type? {",
    "        messageTypes[typeID]",
    "    }",
    "}",
    "",
]
out_path.write_text("\n".join(lines))
print(f"Wrote {out_path} with {len(entries)} entries")
